<?php
  // Сезон
  $season = [
    "зимние",
    "летние",
    "всесезонные"
  ];

  // Состояние
  $sostojanije = [
    "новые",
    "б/у",
    "наварные"
  ];

  // Диаметр R
  $location_array = [
    "R12",
    "R12C",
    "R13",
    "R13C",
    "R14",
    "R14C",
    "R15",
    "R15C",
    "R16",
    "R16.5",
    "R16C",
    "R17",
    "R17.5",
    "R17C",
    "R18",
    "R19",
    "R19.5",
    "R20",
    "R21",
    "R22",
    "R22.5",
    "R23",
    "R24",
    "R24.5",
    "R25"
  ];

  // Высота
  $height_shiny = [
    "12",
    "25",
    "30",
    "35",
    "40",
    "45",
    "50",
    "55",
    "60",
    "65",
    "70",
    "75",
    "80",
    "85",
    "90",
    "95",
    "100",
    "508"
  ];

  // Ширина шин
  $width_shiny = [
    "35",
    "80",
    "90",
    "100",
    "110",
    "115",
    "120",
    "125",
    "130",
    "135",
    "140",
    "145",
    "150",
    "155",
    "160",
    "165",
    "170",
    "175",
    "180",
    "185",
    "190",
    "195",
    "200",
    "205",
    "210",
    "215",
    "220",
    "225",
    "230",
    "235",
    "240",
    "245",
    "250",
    "255",
    "260",
    "265",
    "275",
    "280",
    "285",
    "295",
    "300",
    "305",
    "315",
    "320",
    "325",
    "335",
    "355",
    "385",
    "435",
    "445",
    "455"
  ];


  // Марка
  $marka_shiny = [
    "Accelera",
    "Achilles",
    "Admiral",
    "Advance",
    "Aeolus",
    "Altenzo",
    "Amberway",
    "Amtel",
    "Antares",
    "Aoteli",
    "Aplus",
    "Apollo",
    "Aptany",
    "Arizonian",
    "Arrowspeed",
    "Atlas",
    "Atturo",
    "Aurora",
    "Austone",
    "Autogrip",
    "Autoguard",
    "Avon",
    "Barum",
    "BCT",
    "Berlin",
    "Berliner",
    "BFGoodrich",
    "Blacklion",
    "Blackstone",
    "Blue Streak",
    "Bob Jane",
    "BOTO",
    "Bridgestone",
    "Briway",
    "Camac",
    "Capitol",
    "Carbon Series",
    "Ceat",
    "Centara",
    "Champiro",
    "Chengshan",
    "Clear",
    "Collins",
    "Comforcer",
    "Compasal",
    "Constancy",
    "Continental",
    "Contyre",
    "Cooper",
    "Cordiant",
    "Cratos",
    "Dailyway",
    "Davanti",
    "Dayton",
    "Dean",
    "Debica",
    "Deestone",
    "Definity",
    "Delinte",
    "Delmax",
    "Deruibo",
    "Dextero",
    "Diamondback",
    "DMACK",
    "Double Coin",
    "DoubleStar",
    "Dunlop",
    "Duraturn",
    "Duro",
    "Durun",
    "Effiplus",
    "ESA-Tecar",
    "Eurotec",
    "Event",
    "Evergreen",
    "Excelon",
    "Falken",
    "Farroad",
    "Fate",
    "Federal",
    "Fighter",
    "Firemax",
    "Firenza",
    "Firestone",
    "First Stop",
    "Forceum",
    "Formula",
    "Fortio",
    "Fortuna",
    "Fulda",
    "FullRun",
    "Fullway",
    "Futura",
    "Fuzion",
    "Gauth Pneus",
    "General",
    "General Grabber",
    "Gislaved",
    "Goalstar",
    "Goform",
    "Gold-Gum",
    "GoldWay",
    "Goodride",
    "Goodyear",
    "Gremax",
    "Grenlander",
    "GripMax",
    "GT Radial",
    "Haida",
    "Hankook",
    "Headway",
    "Heidenau",
    "Hercules",
    "Hero",
    "Hifly",
    "Horizon",
    "Ilink",
    "Imperial",
    "Infinity",
    "Invovic",
    "Ironman",
    "Jinyu",
    "Joyroad",
    "Kapsen",
    "Kelly",
    "Kenda",
    "Keter",
    "Kinforest",
    "Kingstar",
    "Kleber",
    "Kormoran",
    "Kumho",
    "Landsail",
    "Lanvigator",
    "Lassa",
    "Laufenn",
    "LingLong",
    "LionHart",
    "Luckyland",
    "Mabor",
    "Marangoni",
    "Marix",
    "Marshal",
    "Master",
    "Mastercraft",
    "Mastersteel",
    "Matador",
    "Maxtrek",
    "Maxxis",
    "Mayrun",
    "Mazzini",
    "Mentor",
    "Metzeler",
    "Michelin",
    "Milestar",
    "Milestone",
    "Minerva",
    "Mirage",
    "Mohawk",
    "MotoMaster",
    "Multi-Mile",
    "Multirac",
    "Nankang",
    "Neolin",
    "Nereus",
    "Nexen",
    "Nika",
    "Nitto",
    "Nokian",
    "Nordman",
    "Opals",
    "Ovation",
    "Pace",
    "Petlas",
    "Pirelli",
    "Platin",
    "Pneumant",
    "Points",
    "Powertrac",
    "Premada",
    "Premiorri",
    "Presa",
    "Prestivo",
    "Primewell",
    "Profil",
    "Radar",
    "Rapid",
    "Regal",
    "Rigdon",
    "Riken",
    "Roadking",
    "Roadstone",
    "RoadX",
    "Rockstone",
    "Rosava",
    "Rotalla",
    "Rotex",
    "Routeway",
    "Rovelo",
    "Runway",
    "Saferich",
    "Sagitar",
    "Sailun",
    "Sailwin",
    "Sava",
    "Securo",
    "Semperit",
    "Silverstone",
    "Sonar",
    "Sonny",
    "Spider",
    "Sportiva",
    "Stampede",
    "Star Performer",
    "Starfire",
    "Starmaxx",
    "Strial",
    "Sumitomo",
    "Sunew",
    "Sunny",
    "Suntek",
    "Sunwide",
    "Supercat",
    "Syron",
    "Taganca",
    "Taurus",
    "TeamStar",
    "Three-a",
    "Tigar",
    "Toledo",
    "Torque",
    "Toyo",
    "Tracmax",
    "Trayal",
    "Trazano",
    "Tri Ace",
    "Triangle",
    "Tristar",
    "Tunga",
    "Tyfoon",
    "TyRex",
    "Uniroyal",
    "Viatti",
    "Viking",
    "Voltyre",
    "Vredestein",
    "Wanli",
    "WestLake",
    "Winda",
    "Windforce",
    "Winrun",
    "Winter Tact",
    "Yokohama",
    "Zeetex",
    "Zeta",
    "Zetum",
    "Белшина",
    "Кама",
    "Кама-Евро",
    "КШЗ",
    "Медведь",
    "Омскшина",
    "Росшина"
  ];


  $versions = [
    "легковые",
    "грузовые",
    "спецтехника",
    "мото",
    "внедорожные"
  ];

    
    // Диаметр J
    $width_array = [
    "5",
    "5.5",
    "6",
    "6.5",
    "7",
    "7.5",
    "8",
    "8.5",
    "9",
    "9.5",
    "10",
    "10.5",
    "11",
    "11.5",
    "12",
    "12.5"
    ];

    // Кол-во отверстий
    $height_array = [
    "3",
    "4",
    "5",
    "6",
    "10"
    ];

    // Расстояние между отверстиями PCD, мм
    $weight_array = [
    "98",
    "100",
    "105",
    "108",
    "110",
    "112",
    "114.3",
    "115",
    "118",
    "120",
    "120.7",
    "127",
    "130",
    "139.7",
    "150",
    "160",
    "161",
    "165.1",
    "170",
    "180",
    "205"
    ];

    // Диаметр центрального отверстия DIA, мм
    $diadiametr_array = [
    "52.1",
    "54.1",
    "56.1",
    "56.6",
    "57.1",
    "58.1",
    "59.1",
    "59.6",
    "60.1",
    "63.4",
    "64.1",
    "65.1",
    "66.1",
    "66.6",
    "67.1",
    "70.1",
    "71.2",
    "72.6",
    "74.1"
    ];

    /* Коробка */
    $upc_array = ["АКПП","МКПП","Робот","Вариатор"]; 

    /* Тип кузова */ 
    $ean_array = ["седан","хэтчбек","универсал","купе","кабриолет","минивэн","пикап","фургон","тягач","лифтбек","внедорожник"]; 